name: ds-bazaar-workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - requests
  - jupyterlab
  - pandas
  - matplotlib
  - psutil
  - fastparquet
  - dask
  - joblib