name: ds-bazaar-workshop
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs
  - pip
  - requests
  - jupyterlab>=2.0.0,<3
  # jedi problem: https://github.com/ipython/ipython/issues/12740
  - jedi<0.18.0
  - pandas
  - matplotlib
  - psutil
  - fastparquet
  - python-snappy
  - dask
  - python-graphviz
  - joblib
  - geopandas
  - descartes
